### ISSUE TITLE
About travelling salesman problem running example?

### ISSUE THREAD

**Issue by htomtom** [Clymsw/PopOptBox#1]
In the HyperParameterTuning project, there is a ContinuousProblem example. But there isn't any  travelling salesman problem example. How to run a tsp example with the evolutionary algorithm? If some tsp running example is added, it will be more useful to test the project.

**Comment by Clymsw** [comment]
It is true the HyperParameterTuning client does not have much content yet.  It needs rewriting and extension if it is to serve as a useful tool, rather than just a sandbox.
Regarding TSP:
 1) In the Problems project, there are TSP examples which can be used as evaluators.
 2) Writing a good GA/EA for the TSP is not straightforward.  The problem space needs to be chosen carefully to enable good solutions to be generated.  Rule-learning GAs seem to have the most success. A poorly-performing GA, can however be written easily, simply using the order of the cities as the decision vector.  I haven't yet implemented a suitable (permutation-safe) crossover operator for this yet though.
 3) Feel free to contribute!
